name: Save Docker image as artifact

on:
  workflow_dispatch:

jobs:
  save-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Save Docker image as artifact
        run: |
          docker save -o image.tar btap-ml-cpu
          mkdir -p ./artifacts
          mv image.tar ./artifacts/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-mas-btap-1
          path: ./artifacts/image.tar